// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Octockup.Server.Database;

#nullable disable

namespace Octockup.Server.Migrations.Sqlite
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20260711073003_ScopeTagsByUser")]
    partial class ScopeTagsByUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Octockup.Server.Database.Backup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("DisableCompression")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disable_compression");

                    b.Property<bool>("DisableEncryption")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disable_encryption");

                    b.PrimitiveCollection<string>("IgnoredPaths")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ignored_paths");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_id");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tag");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("StorageId");

                    b.HasIndex("UserId", "Tag")
                        .IsUnique();

                    b.ToTable("backups");
                });

            modelBuilder.Entity("Octockup.Server.Database.DownloadTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ConsumedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("consumed_at");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IncludeFiles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("include_files");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_id");

                    b.Property<Guid?>("SecondaryResourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("secondary_resource_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("download_tickets");
                });

            modelBuilder.Entity("Octockup.Server.Database.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveStorageOperationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("active_storage_operation_id");

                    b.Property<int?>("ActiveStorageOperationKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active_storage_operation_kind");

                    b.Property<string>("BackupModuleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("backup_module_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Destination")
                        .HasColumnType("INTEGER")
                        .HasColumnName("destination");

                    b.Property<string>("EncryptedParameters")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("encrypted_parameters");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("parameters");

                    b.Property<string>("StorageOperationLeaseExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_operation_lease_expires_at");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tag");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Tag")
                        .IsUnique();

                    b.ToTable("modules");
                });

            modelBuilder.Entity("Octockup.Server.Database.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("ReadAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("read_at");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Octockup.Server.Database.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("family_id");

                    b.Property<int?>("RevocationReason")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revocation_reason");

                    b.Property<string>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("FamilyId", "RevokedAt");

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("refresh_sessions");
                });

            modelBuilder.Entity("Octockup.Server.Database.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BackupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("backup_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<TimeSpan?>("Interval")
                        .HasColumnType("TEXT")
                        .HasColumnName("interval");

                    b.Property<string>("StartAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("start_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BackupId");

                    b.ToTable("schedules");
                });

            modelBuilder.Entity("Octockup.Server.Database.Snapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BackupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("backup_id");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("FilesCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("files_count");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_size");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BackupId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("snapshots");
                });

            modelBuilder.Entity("Octockup.Server.Database.SnapshotFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string>("ChunkHashes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("chunk_hashes");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Hashsum")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hashsum");

                    b.Property<string>("LastModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Path")
                        .IsUnique();

                    b.ToTable("snapshot_files");
                });

            modelBuilder.Entity("Octockup.Server.Database.StorageCleanupJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveStorageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("active_storage_id");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cancellation_requested");

                    b.Property<long>("ChunkObjectsScanned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chunk_objects_scanned");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_path");

                    b.Property<long>("DeletedObjects")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted_objects");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<long>("FailedDeletes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_deletes");

                    b.Property<string>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<long>("FreedBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("freed_bytes");

                    b.Property<long>("MissingObjects")
                        .HasColumnType("INTEGER")
                        .HasColumnName("missing_objects");

                    b.Property<long>("OrphanBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("orphan_bytes");

                    b.Property<long>("OrphanObjects")
                        .HasColumnType("INTEGER")
                        .HasColumnName("orphan_objects");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phase");

                    b.Property<long>("ReferenceCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reference_count");

                    b.Property<long>("ReferencedBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("referenced_bytes");

                    b.Property<long>("ReferencedChunks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("referenced_chunks");

                    b.Property<long>("ReferencedObjects")
                        .HasColumnType("INTEGER")
                        .HasColumnName("referenced_objects");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<long>("SkippedObjects")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skipped_objects");

                    b.Property<long>("SnapshotFilesScanned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("snapshot_files_scanned");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<long>("StorageBytesScanned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("storage_bytes_scanned");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_id");

                    b.Property<long>("StorageObjectsScanned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("storage_objects_scanned");

                    b.Property<string>("StorageTag")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_tag");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("UploadedHashRowsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uploaded_hash_rows_deleted");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActiveStorageId")
                        .IsUnique();

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("storage_cleanup_jobs");
                });

            modelBuilder.Entity("Octockup.Server.Database.UploadedHash", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("CompressionAlgorithm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("compression_algorithm");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("module_id");

                    b.Property<long>("OriginalSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("original_size");

                    b.Property<long>("StoredSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stored_size");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Hash");

                    b.HasIndex("ModuleId", "Hash")
                        .IsUnique();

                    b.ToTable("uploaded_hashes");
                });

            modelBuilder.Entity("Octockup.Server.Database.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordPhc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_phc");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Octockup.Server.Database.Backup", b =>
                {
                    b.HasOne("Octockup.Server.Database.Module", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Octockup.Server.Database.Module", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("Octockup.Server.Database.Module", b =>
                {
                    b.HasOne("Octockup.Server.Database.User", "User")
                        .WithMany("Modules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Octockup.Server.Database.Notification", b =>
                {
                    b.HasOne("Octockup.Server.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Octockup.Server.Database.RefreshSession", b =>
                {
                    b.HasOne("Octockup.Server.Database.User", "User")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Octockup.Server.Database.Schedule", b =>
                {
                    b.HasOne("Octockup.Server.Database.Backup", "Backup")
                        .WithMany("Schedules")
                        .HasForeignKey("BackupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Backup");
                });

            modelBuilder.Entity("Octockup.Server.Database.Snapshot", b =>
                {
                    b.HasOne("Octockup.Server.Database.Backup", "Backup")
                        .WithMany("Snapshots")
                        .HasForeignKey("BackupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Octockup.Server.Database.Schedule", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("ScheduleId");

                    b.Navigation("Backup");
                });

            modelBuilder.Entity("Octockup.Server.Database.SnapshotFile", b =>
                {
                    b.HasOne("Octockup.Server.Database.Snapshot", "Snapshot")
                        .WithMany("Files")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Octockup.Server.Database.UploadedHash", b =>
                {
                    b.HasOne("Octockup.Server.Database.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Octockup.Server.Database.Backup", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Octockup.Server.Database.Schedule", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Octockup.Server.Database.Snapshot", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Octockup.Server.Database.User", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("RefreshSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
