// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Octockup.Server.Database;

#nullable disable

namespace Octockup.Server.Migrations.Postgres
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20260711075302_AddIndexedScheduleNextRun")]
    partial class AddIndexedScheduleNextRun
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Octockup.Server.Database.Backup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DisableCompression")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_compression");

                    b.Property<bool>("DisableEncryption")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_encryption");

                    b.PrimitiveCollection<string[]>("IgnoredPaths")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("ignored_paths");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_id");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("StorageId");

                    b.HasIndex("UserId", "Tag")
                        .IsUnique();

                    b.ToTable("backups");
                });

            modelBuilder.Entity("Octockup.Server.Database.DownloadTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IncludeFiles")
                        .HasColumnType("boolean")
                        .HasColumnName("include_files");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<Guid?>("SecondaryResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("secondary_resource_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("download_tickets");
                });

            modelBuilder.Entity("Octockup.Server.Database.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveStorageOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_storage_operation_id");

                    b.Property<int?>("ActiveStorageOperationKind")
                        .HasColumnType("integer")
                        .HasColumnName("active_storage_operation_kind");

                    b.Property<string>("BackupModuleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backup_module_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Destination")
                        .HasColumnType("integer")
                        .HasColumnName("destination");

                    b.Property<string>("EncryptedParameters")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_parameters");

                    b.Property<Dictionary<string, string>>("Parameters")
                        .IsRequired()
                        .HasColumnType("hstore")
                        .HasColumnName("parameters");

                    b.Property<DateTime?>("StorageOperationLeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("storage_operation_lease_expires_at");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Tag")
                        .IsUnique();

                    b.ToTable("modules");
                });

            modelBuilder.Entity("Octockup.Server.Database.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Octockup.Server.Database.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<int?>("RevocationReason")
                        .HasColumnType("integer")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("FamilyId", "RevokedAt");

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("refresh_sessions");
                });

            modelBuilder.Entity("Octockup.Server.Database.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BackupId")
                        .HasColumnType("uuid")
                        .HasColumnName("backup_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<TimeSpan?>("Interval")
                        .HasColumnType("interval")
                        .HasColumnName("interval");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BackupId");

                    b.HasIndex("NextRunAt");

                    b.ToTable("schedules");
                });

            modelBuilder.Entity("Octockup.Server.Database.Snapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BackupId")
                        .HasColumnType("uuid")
                        .HasColumnName("backup_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FilesCount")
                        .HasColumnType("integer")
                        .HasColumnName("files_count");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalSize")
                        .HasColumnType("bigint")
                        .HasColumnName("total_size");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BackupId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("snapshots");
                });

            modelBuilder.Entity("Octockup.Server.Database.SnapshotFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("ChunkHashes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("chunk_hashes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hashsum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashsum");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Path")
                        .IsUnique();

                    b.ToTable("snapshot_files");
                });

            modelBuilder.Entity("Octockup.Server.Database.StorageCleanupJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveStorageId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_storage_id");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("cancellation_requested");

                    b.Property<long>("ChunkObjectsScanned")
                        .HasColumnType("bigint")
                        .HasColumnName("chunk_objects_scanned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentPath")
                        .HasColumnType("text")
                        .HasColumnName("current_path");

                    b.Property<long>("DeletedObjects")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_objects");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<long>("FailedDeletes")
                        .HasColumnType("bigint")
                        .HasColumnName("failed_deletes");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("FreedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("freed_bytes");

                    b.Property<long>("MissingObjects")
                        .HasColumnType("bigint")
                        .HasColumnName("missing_objects");

                    b.Property<long>("OrphanBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("orphan_bytes");

                    b.Property<long>("OrphanObjects")
                        .HasColumnType("bigint")
                        .HasColumnName("orphan_objects");

                    b.Property<int>("Phase")
                        .HasColumnType("integer")
                        .HasColumnName("phase");

                    b.Property<long>("ReferenceCount")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_count");

                    b.Property<long>("ReferencedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("referenced_bytes");

                    b.Property<long>("ReferencedChunks")
                        .HasColumnType("bigint")
                        .HasColumnName("referenced_chunks");

                    b.Property<long>("ReferencedObjects")
                        .HasColumnType("bigint")
                        .HasColumnName("referenced_objects");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<long>("SkippedObjects")
                        .HasColumnType("bigint")
                        .HasColumnName("skipped_objects");

                    b.Property<long>("SnapshotFilesScanned")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_files_scanned");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("StorageBytesScanned")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_bytes_scanned");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_id");

                    b.Property<long>("StorageObjectsScanned")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_objects_scanned");

                    b.Property<string>("StorageTag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_tag");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UploadedHashRowsDeleted")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_hash_rows_deleted");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActiveStorageId")
                        .IsUnique();

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("storage_cleanup_jobs");
                });

            modelBuilder.Entity("Octockup.Server.Database.UploadedHash", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompressionAlgorithm")
                        .HasColumnType("integer")
                        .HasColumnName("compression_algorithm");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<long>("OriginalSize")
                        .HasColumnType("bigint")
                        .HasColumnName("original_size");

                    b.Property<long>("StoredSize")
                        .HasColumnType("bigint")
                        .HasColumnName("stored_size");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Hash");

                    b.HasIndex("ModuleId", "Hash")
                        .IsUnique();

                    b.ToTable("uploaded_hashes");
                });

            modelBuilder.Entity("Octockup.Server.Database.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordPhc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_phc");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Octockup.Server.Database.Backup", b =>
                {
                    b.HasOne("Octockup.Server.Database.Module", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Octockup.Server.Database.Module", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("Octockup.Server.Database.Module", b =>
                {
                    b.HasOne("Octockup.Server.Database.User", "User")
                        .WithMany("Modules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Octockup.Server.Database.Notification", b =>
                {
                    b.HasOne("Octockup.Server.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Octockup.Server.Database.RefreshSession", b =>
                {
                    b.HasOne("Octockup.Server.Database.User", "User")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Octockup.Server.Database.Schedule", b =>
                {
                    b.HasOne("Octockup.Server.Database.Backup", "Backup")
                        .WithMany("Schedules")
                        .HasForeignKey("BackupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Backup");
                });

            modelBuilder.Entity("Octockup.Server.Database.Snapshot", b =>
                {
                    b.HasOne("Octockup.Server.Database.Backup", "Backup")
                        .WithMany("Snapshots")
                        .HasForeignKey("BackupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Octockup.Server.Database.Schedule", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("ScheduleId");

                    b.Navigation("Backup");
                });

            modelBuilder.Entity("Octockup.Server.Database.SnapshotFile", b =>
                {
                    b.HasOne("Octockup.Server.Database.Snapshot", "Snapshot")
                        .WithMany("Files")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Octockup.Server.Database.UploadedHash", b =>
                {
                    b.HasOne("Octockup.Server.Database.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Octockup.Server.Database.Backup", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Octockup.Server.Database.Schedule", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Octockup.Server.Database.Snapshot", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Octockup.Server.Database.User", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("RefreshSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
